# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9760d0c438852a6ce8734678fd0d4b9a4b7383cc3df560ef4fdd715c9cc51160aba6bcb9f8dd37f49da6110fb01b8a184e766bd71eb04d454943b16c1ebefbe5

test:
  secret_key_base: 610b3638f87ac227243368b3a650afea442352adb956c971bee6fe0131e813743cb71da66c4a0e333a18d2b2f0f2f1f4aae0f0e6dd8030c834dff157ec7fe1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
